### ISSUE TITLE
Only able to work with 4 taps

### ISSUE THREAD

**Issue by farcouet** [bgulla/boozer#22]
Hello,
There seems to be something missing to add more than 4 taps. I tried to modify the beer_db.py to add it there but I still get the following error:
2020-04-12 20:16:07,530 root         INFO     Tap 1: Setting capacity to 5
2020-04-12 20:16:07,537 bar_mqtt     INFO     mqtt topic updated: topic: bar/tap1/value | value: 100.0
2020-04-12 20:16:07,542 bar_mqtt     INFO     mqtt topic updated: topic: bar/tap1/beverage | value: Cidre
2020-04-12 20:16:07,544 root         INFO     Tap 2: Setting capacity to 5
2020-04-12 20:16:07,550 bar_mqtt     INFO     mqtt topic updated: topic: bar/tap2/value | value: 100.0
2020-04-12 20:16:07,556 bar_mqtt     INFO     mqtt topic updated: topic: bar/tap2/beverage | value: Blanche
2020-04-12 20:16:07,558 root         INFO     Tap 3: Setting capacity to 5
2020-04-12 20:16:07,563 bar_mqtt     INFO     mqtt topic updated: topic: bar/tap3/value | value: 100.0
2020-04-12 20:16:07,569 bar_mqtt     INFO     mqtt topic updated: topic: bar/tap3/beverage | value: Erable
2020-04-12 20:16:07,571 root         INFO     Tap 4: Setting capacity to 5
2020-04-12 20:16:07,577 bar_mqtt     INFO     mqtt topic updated: topic: bar/tap4/value | value: 99.015
2020-04-12 20:16:07,582 bar_mqtt     INFO     mqtt topic updated: topic: bar/tap4/beverage | value: NEIPA
2020-04-12 20:16:07,584 root         INFO     Tap 5: Setting capacity to 5
Traceback (most recent call last):
  File "boozer.py", line 525, in <module>
    main()
  File "boozer.py", line 520, in main
    boozer = Boozer()
  File "boozer.py", line 259, in __init__
    self.update_mqtt(tap, beverage_name=new_tap.get_beverage_name())
  File "boozer.py", line 286, in update_mqtt
    percent = self.db.get_percentage100(tap_id)
  File "/boozer/beer_db.py", line 61, in get_percentage100
    return self.get_percentage(tap_id) * 100
  File "/boozer/beer_db.py", line 50, in get_percentage
    volume_expelled = self.get_tap(tap_id)
  File "/boozer/beer_db.py", line 111, in get_tap
    return volume
UnboundLocalError: local variable 'volume' referenced before assignment

**Comment by farcouet** [comment]
Ok I just added an entry in the beer table using sqlite and it works.

**Comment by bgulla** [comment]
I think there might be a limit of 10 or 100, I need to go in and check. We can easily disable that though.
